name: First Workflow

#manually trigger the workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hola world"
      - name: Print Goodbye 
        run: echo "done"
    
